POST http://localhost:5000/user/register                                                                              
Content-Type: application/json

{
    "nom":"b",
    "prenom":"b",
    "pseudonyme":"b",
    "email":"b",
    "password":"b"
}

###

POST http://localhost:5000/user/login                                                                              
Content-Type: application/json

{
    "email":"b",
    "password":"b"
}

###

POST http://localhost:5000/post/creerPost
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NjJhZWM4MTRmYjZkZTg2YzVjMGZmMCIsInJvbGUiOiJ1dGlsaXNhdGV1ciIsImJhbm5pcyI6ZmFsc2UsImlhdCI6MTc1MTM3MDcwNX0.XRDa0j6bT6TOSMUj5tsffPPLbpJXrkbgMiALLbngfXM

{
    "categorie":"MTT",
    "titre":"hey"
}

###

GET  http://localhost:5000/post
Content-Type: application/json

###

POST http://localhost:5000/Message/creerMessage/6869a01d21c3b7454a276589
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NjJhZWM4MTRmYjZkZTg2YzVjMGZmMCIsInJvbGUiOiJ1dGlsaXNhdGV1ciIsImJhbm5pcyI6ZmFsc2UsImlhdCI6MTc1MTQ4OTA4OH0.SBMy26qCsUwiPwGPmazfXbwYG-uuIGh4WKJj-kW9cWI

{
    "contenu":" bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour bonjour"
}

###

GET http://localhost:5000/Message/messagePost/68592d633d3cc437581bed68
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NTkxMmJlODg3Zjg2Y2E1MTY0ODllZSIsInJvbGUiOiJ1dGlsaXNhdGV1ciIsImJhbm5pcyI6ZmFsc2UsImlhdCI6MTc1MDY3NDA4NH0.9e0RHyOV1wZYvH5apJ4EZNjK58PhijSc2bAJOAFq2Ik

###

POST http://localhost:5000/Categorie/creerCategorie
Content-Type: application/json

{
    "titre":"Règles",
    "contenu":"Discussion sur les règles du poker."
}

###

GET  http://localhost:5000/Categorie/afficherAllCategories
Content-Type: application/json

###

GET  http://localhost:5000/post/posteParCategorie/MTT
Content-Type: application/json

###

GET  http://localhost:5000/post/lePoste/68668c0924307d7ad83ef4ea
Content-Type: application/json

###

GET  http://localhost:5000/post/recherchepostesParPseudo/bobyaa
Content-Type: application/json


###

GET  http://localhost:5000/post/recherchepostesParmot/bon
Content-Type: application/json






